# Create a new comment
POST http://localhost:3001/api/comments/create HTTP/1.1
Content-Type: application/json

{
  "message": "Heloooooooooo",
  "userId": "11773",
  "taskId": "1"
}

###
# Get comment by ID
GET http://localhost:3004/api/comments/1 HTTP/1.1

###
# Get all comments and filtres
GET http://localhost:3004/api/comments?limit=2&page=2 HTTP/1.1

###