# Upload some file
POST http://localhost:3006/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="cat.jpg"

< project/apps/uploader/src/app/file/cat.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Get file by ID
GET http://localhost:3000/api/files/64dcd9b5c84a0f6555b81041 HTTP/1.1

###