###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###-----------------------------------------------------------------------------------------------------------------------------------------------------USERS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Create a new user
POST http://localhost:3002/api/users/create HTTP/1.1
Content-Type: application/json

{
  "email": "exec@gmail.local",
  "dateBirth": "2002-02-22",
  "firstname": "Keks",
  "lastname": "Smith",
  "city": "Moscow",
  "password": "123456",
  "role": "Executor",
  "specialization": ["sd", "scsac", "sacasc", "scasc", "ascc"],
  "userInformation":"Person"
  }

###
# Login user by email and password
POST http://localhost:3002/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "client@gmail.local",
  "password": "123456"
}

###

# Update user
PATCH http://localhost:3002/api/users/update/64ef8143783a7c56ce7be7ea HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGVmODE0Mzc4M2E3YzU2Y2U3YmU3ZWEiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiVml0YWwiLCJpYXQiOjE2OTM0MjI0NzAsImV4cCI6MTY5MzUwODg3MH0.5ctZgiMNaWzaUeY_nFJRP7Rp6JSXr3CJ9bR6acIMMr0
Content-Type: application/json

{
  "dateBirth": "2005-02-22",
  "firstname": "Vital",
  "lastname": "c0manch3",
  "city": "SaintPetersburg",
  "specialization": ["sd", "scsac", "sacasc", "scasc"],
  "userInformation":"Per"
}

###
###
# Create a new password
POST http://localhost:3002/api/users/newpsw HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "1234567",
  "newPassword": "123456"
}
###

# Get user by ID
GET http://localhost:3002/api/users/64f34de1fce8e56ae10a620b HTTP/1.1
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###-----------------------------------------------------------------------------------------------------------------------------------------------------TASKS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Create a new task
POST http://localhost:3002/api/tasks/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzMWM5ZDRkNzcyMWVhYTE1ZWZhNjAiLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5sb2NhbCIsInJvbGUiOiJDbGllbnQiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY1NDE5MCwiZXhwIjoxNjkzNzQwNTkwfQ.cUXI_f8C0yKuOdb9lzbzG7TKrh39v5iETa01IGgO-PA
Content-Type: application/json

{
  "title": "Find Cat",
  "description": "Find the best cat in the world",
  "category": "1",
  "price": "10",
  "deadline": "2023-10-22",
  "address": "Yokogama st.",
  "city": "SaintPetersburg",
  "tags": ["x23","MMMM", "fcwec", "wdqwd", "wdqwd"]
}

###

# Get task by ID
GET http://localhost:3002/api/tasks/2 HTTP/1.1
###

# Get all New tasks and filtres
POST http://localhost:3002/api/tasks/new?sortDirection=desc&limit=5&page=1&sortBy=commentsCount HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzNGRlMWZjZThlNTZhZTEwYTYyMGIiLCJlbWFpbCI6ImV4ZWNAZ21haWwubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY2NjgwNCwiZXhwIjoxNjkzNzUzMjA0fQ.F3UJthQPsi10R-n3W63cYG-28aJLcSsW3XDZMSueFV0
###

# Get all user tasks 
POST http://localhost:3002/api/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzNGRlMWZjZThlNTZhZTEwYTYyMGIiLCJlbWFpbCI6ImV4ZWNAZ21haWwubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY2NjgwNCwiZXhwIjoxNjkzNzUzMjA0fQ.F3UJthQPsi10R-n3W63cYG-28aJLcSsW3XDZMSueFV0
###

# Update a task
PATCH http://localhost:3002/api/tasks/update/37 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGVmODE0Mzc4M2E3YzU2Y2U3YmU3ZWEiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6ImMwbWFuY2gzIiwiZmlyc3RuYW1lIjoiVml0YWwiLCJpYXQiOjE2OTM1MTIwMDgsImV4cCI6MTY5MzU5ODQwOH0.7GgXm1dyfERiNoQE0RfiE-CTZ3PONooQySxETefRIb0
Content-Type: application/json

{
  "title": "Just C",
  "deadline": "2024-12-22",
  "tags": ["x23","r5f", "GGGG", "GGGG"]

}
###

# Change task-status
PATCH http://localhost:3002/api/tasks/status/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzMWM5ZDRkNzcyMWVhYTE1ZWZhNjAiLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5sb2NhbCIsInJvbGUiOiJDbGllbnQiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY1NDE5MCwiZXhwIjoxNjkzNzQwNTkwfQ.cUXI_f8C0yKuOdb9lzbzG7TKrh39v5iETa01IGgO-PA
Content-Type: application/json

{
  "status": "Done",
  "executorId": "64f34de1fce8e56ae10a620b"
  
}

###
# Add new response
POST http://localhost:3002/api/tasks/response/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzNGRlMWZjZThlNTZhZTEwYTYyMGIiLCJlbWFpbCI6ImV4ZWNAZ21haWwubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY2NjgwNCwiZXhwIjoxNjkzNzUzMjA0fQ.F3UJthQPsi10R-n3W63cYG-28aJLcSsW3XDZMSueFV0
###
# Delete task by Id
POST http://localhost:3002/api/tasks/delete/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzMWM5ZDRkNzcyMWVhYTE1ZWZhNjAiLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5sb2NhbCIsInJvbGUiOiJDbGllbnQiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY1NDE5MCwiZXhwIjoxNjkzNzQwNTkwfQ.cUXI_f8C0yKuOdb9lzbzG7TKrh39v5iETa01IGgO-PA
####
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###-----------------------------------------------------------------------------------------------------------------------------------------------------COMMENTS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Create a new comment
POST http://localhost:3002/api/comments/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYxZDA5NDJjMmE1MThhNDdjNzIyNTciLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5sb2NhbCIsInJvbGUiOiJDbGllbnQiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzU2OTE5NywiZXhwIjoxNjkzNjU1NTk3fQ.kZQrGRE0MIqquuFe3emLNp6IxJvGgKCLghGvp2rM_wY
Content-Type: application/json

{
  "message": "Heloooooooooo!!!",
  "taskId": "47"
}
###
# Get comment by ID
GET http://localhost:3002/api/comments/5 HTTP/1.1

###
# Get all comments and filtres
GET http://localhost:3002/api/comments?limit=3&page=2 HTTP/1.1

###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###-----------------------------------------------------------------------------------------------------------------------------------------------------REVIEWS--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

# Create a new review
POST http://localhost:3002/api/reviews/create/10 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzMWM5ZDRkNzcyMWVhYTE1ZWZhNjAiLCJlbWFpbCI6ImNsaWVudEBnbWFpbC5sb2NhbCIsInJvbGUiOiJDbGllbnQiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY1NDE5MCwiZXhwIjoxNjkzNzQwNTkwfQ.cUXI_f8C0yKuOdb9lzbzG7TKrh39v5iETa01IGgO-PA
Content-Type: application/json

{
  "message": "Super",
  "grade": "4"
}

###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###-----------------------------------------------------------------------------------------------------------------------------------------------------CATEGORY--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
###---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Create new caterory
POST http://localhost:3002/api/categories/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGYzNGRlMWZjZThlNTZhZTEwYTYyMGIiLCJlbWFpbCI6ImV4ZWNAZ21haWwubG9jYWwiLCJyb2xlIjoiRXhlY3V0b3IiLCJsYXN0bmFtZSI6IlNtaXRoIiwiZmlyc3RuYW1lIjoiS2VrcyIsImlhdCI6MTY5MzY2NjgwNCwiZXhwIjoxNjkzNzUzMjA0fQ.F3UJthQPsi10R-n3W63cYG-28aJLcSsW3XDZMSueFV0
Content-Type: application/json

{
  "title": "pats"
}
###
# Get all categories
GET http://localhost:3002/api/categories HTTP/1.1

###