# Create a new task
POST http://localhost:3000/api/tasks/create HTTP/1.1
Content-Type: application/json

{
  "title": "Find Cat",
  "description": "Find the best cat in the world",
  "category": "2",
  "price": "10",
  "deadline": "2023-10-22",
  "address": "Yokogama st.",
  "city": "SaintPetersburg",
  "tags": ["x23","MMMM", "fcwec", "wdqwd", "wdqwd"],
  "creatorId": "64f0da92fadc115baf083e7b"
}

###

# Get task by ID
GET http://localhost:3000/api/tasks/2 HTTP/1.1

###
# Update a task
PATCH http://localhost:3000/api/tasks/update/3 HTTP/1.1
Content-Type: application/json

{
  "title": "Just Cat",
  "deadline": "2024-12-22",
  "tags": ["x23","r5f", "GGGG", "GGGG"]

}

###

# Get all New tasks and filtres
GET http://localhost:3000/api/tasks/new?sortDirection=desc&limit=5&page=1&sortBy=commentsCount&catigories=1,2 HTTP/1.1

###
# Change task-status
PATCH http://localhost:3000/api/tasks/status/45 HTTP/1.1
Content-Type: application/json

{
  "status": "InWork",
  "executorId": "64f1d75b2c2a518a47c72260"
  
}

###
# Get all new tasks
GET http://localhost:3000/api/tasks/new HTTP/1.1

###
# Add new response
PATCH http://localhost:3000/api/tasks/response/45 HTTP/1.1
Content-Type: application/json

{
  "executorId": "64f1d75b2c2a518a47c72260"
}
###
# Get executor info
GET http://localhost:3000/api/tasks/executor/info/64f31d9c4d7721eaa15efa67 HTTP/1.1

###
# Get client info
GET http://localhost:3000/api/tasks/client/info/64f31c9d4d7721eaa15efa60 HTTP/1.1

###
# Get all client tasks
GET http://localhost:3000/api/tasks/client/tasks/64f31c9d4d7721eaa15efa60?status=New HTTP/1.1

###
# Get all executor tasks
GET http://localhost:3000/api/tasks/executor/tasks/64f31d9c4d7721eaa15efa67 HTTP/1.1

###
# Delete task by Id
POST http://localhost:3000/api/tasks/delete/4 HTTP/1.1
####