# Create a new user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "dateBirth": "2012-02-22",
  "firstname": "Keks",
  "lastname": "Smith",
  "city": "StP",
  "password": "123456",
  "role": "client"
}

###

# Get user by ID
GET http://localhost:3000/api/auth/64c8bcee20c004151c13824e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NGM4YmNlZTIwYzAwNDE1MWMxMzgyNGUiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY2xpZW50IiwibGFzdG5hbWUiOiJTbWl0aCIsImZpcnN0bmFtZSI6Iktla3MiLCJpYXQiOjE2OTIyMDk4NDgsImV4cCI6MTY5MjI5NjI0OH0.GebbIaotc1Z52XVfzomgrOkrPCm8GoUGt_98VjVlwNA
###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "123456"
}

###